### ISSUE TITLE
The behavior for Date objects stored in Firestore is going to change

### ISSUE THREAD

**Issue by marcoshuck** [gdg-tangier/vue-firestore#11]
Hi there, I want to share this error I have been getting when I try to test my firestore with my vuejs app

**Console log**
```@firebase/firestore: Firestore (4.13.0): 
The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the
following code to your app before calling any other Cloud Firestore methods:

  const firestore = firebase.firestore();
  const settings = {/* your settings... */ timestampsInSnapshots: true};
  firestore.settings(settings);

With this change, timestamps stored in Cloud Firestore will be read back as
Firebase Timestamp objects instead of as system Date objects. So you will also
need to update code expecting a Date to instead expect a Timestamp. For example:

  // Old:
  const date = snapshot.get('created_at');
  // New:
  const timestamp = snapshot.get('created_at');
  const date = timestamp.toDate();

Please audit all existing usages of Date when you enable the new behavior. In a
future release, the behavior will change to the new behavior, so if you do not
follow these steps, YOUR APP MAY BREAK.
```

**api.js**

```javascript

import Firebase from '@firebase/app'
import '@firebase/firestore'
import config from './config'

const firebaseApp = Firebase.initializeApp(config, {
  timestampsInSnapshots: true
})

const api = firebaseApp.firestore()

export default api
```

**main.js**
```javascript
import Vue from 'vue'
import App from './App.vue'
import Firestore from 'vue-firestore'

Vue.use(Firestore)

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

The view renders but there is no content from firestore.

Hope you can help me!!

Greetings from Argentina.

**Comment by skndungu** [comment]
This Worked liked charm for mine after some pieces of struggle, Thanks @marcoshuck I borrowed alot from your post

import firebase from '@firebase/app'
import 'firebase/firestore'
import firebaseConfig from './firebaseConfig'
const firebaseApp = firebase.initializeApp(firebaseConfig)
export default firebaseApp.firestore()
const api = firebaseApp.firestore()
api.settings({timestampsInSnapshots: true})

**Comment by skndungu** [comment]
In my firebaseInit.js file I changed it to this and its very awesome now

**Comment by skndungu** [comment]
In my firebaseInit.js file I changed it to this and its very awesome now

import firebase from '@firebase/app'
import '@firebase/firestore'
import firebaseConfig from './firebaseConfig'
const firebaseApp = firebase.initializeApp(firebaseConfig)

const api = firebaseApp.firestore()
api.settings({timestampsInSnapshots: true})
export default api
