### ISSUE TITLE
Do Firestore bindings persist across an app?

### ISSUE THREAD

**Issue by sejr** [gdg-tangier/vue-firestore#12]
Say I bind a reference to some collection in component A. Can I then reference that collection in component B with this.$firestore? Or do I have to bind the collection in component B as well?

**Comment by amranidev** [comment]
Hello @sejr 
each Vue component is independent of other, in fact, you cant just bind that collection in each component.

Another way you can do that is to reference that collection in the Main Vue instance so you can use it across all your app components by calling `this.$firestore.myCollection`.

**Comment by reneroth** [comment]
@amranidev Could we get a simple example on how to do this? It seems I am stuck - neither defining the method `firestore` nor `$firestore` on Vue instantiation lets me access the collections in sub-components.

**Comment by reneroth** [comment]
To answer my own question: When the firestore method is implemented in the main instance, components can access the collections by calling `this.$root.$firestore.collection` and the reactive variables by simply calling `this.$root.collection`
