### ISSUE TITLE
querySnapshot.docChanges changed from property to method.

### ISSUE THREAD

**Issue by melvinkcx** [gdg-tangier/vue-firestore#14]
The docChanges property of querySnapshot is no longer a property but a method, so it should be accessed with a bracket (). I wanted to create a pull request but somehow my machine is not able to run npm install successfully. Can someone please reflect the latest API into the repo?

https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot

**Comment by amranidev** [comment]
@melvinkcx, the issue has been resolved, please make sure to update vue-firestore to (v0.2.8).
Thank you :)
