### ISSUE TITLE
collection within document is not retrieved.

### ISSUE THREAD

**Issue by melvinkcx** [gdg-tangier/vue-firestore#17]
There is an issue when binding a document into vue. The fields of the document is properly retrieved. However, any sub-collection(nested collection in a doc) is not retrieved.

**Comment by amranidev** [comment]
Hi @melvinkcx.
Its normal, when you bind a document it will be retrieved as bindable data record (array or object).
`vue-firestore` comes in place to help you bind docs/collections to multiple resources, so make sure that you bind all the docs/collection you need.
Thank you!
