### ISSUE TITLE
Binding firestore collectionReference to Vuex store state

### ISSUE THREAD

**Issue by melvinkcx** [gdg-tangier/vue-firestore#18]
Is that possible to bind a firestore collectionReference to Vuex.Store state instead of the data of the root Vue instance? If so, how would the syntax be like? Thanks.

**Comment by amranidev** [comment]
Hi @melvinkcx.

Basically, you can only initialize your firebase app in the `vue-store`and then use the Firestore source as a state.

- In your store.js file.

```javascript

// initialize firebase.
constfirebaseApp =  firebase.initializeApp(config);
// firestore source.
const firestore = firebase.firestore();

export default new Vuex.Store({
    // states
    state: {
        firestore: firestore
    }
})
```

- In your component

```javascript
export default {
    firestore() {
        return {
            data: this.$store.state.firestore.collection('data')
        }
    },
    data() {
        return {
            // data
        }
    }
}
```

Thank you!

**Comment by ramstein74** [comment]
what about $binding

is this valid?
export default {
    firestore() {
        return {
            reptiles: this.$store.state.firestore.collection('reptiles')
        }
    },
    data() {
        return {
            reptiles:[]
        }
    }
,mounted(){
              this.$binding("reptiles", this.reptiles)
            .then((reptile) => {
                            }).catch(err=>{console.log(err)})
}
