### ISSUE TITLE
this.$unbind is not a function v0.2.8

### ISSUE THREAD

**Issue by benjaminpwarren** [gdg-tangier/vue-firestore#19]
v0.2.8 throws an error when switching components, due to the addition of the beforeDestroy() code that references this.$unbind (I couldn't find this method anywhere in your source).

**Comment by amranidev** [comment]
Hi @benjaminpwarren, thanks for reporting this bug, fixed with `v0.2.9`.

Let me know if you find any other issue.

Thanks a lot!
