### ISSUE TITLE
How to trigger an event after db.collection('mycoll') is called ?

### ISSUE THREAD

**Issue by ramstein74** [gdg-tangier/vue-firestore#23]
How to trigger an event after db.collection('mycoll') is called ?

I´m using a vuetify data-table with the loading indicator and need to set it to false after the table is populated.

regards

**Comment by amranidev** [comment]
Hi @ramstein74 Thank for opening this issue.

Basically, you can bind your collection manually by calling `bindings` which returns a promise, once the promise is resolved, you can write the logic you want.

```javascript
....
mounted () {
    var source = firebase.firestore().collection("MyCollection")
    this.$binding('MyCollection', source).then((collection) => {
       // write the logic
    })
}
....
````

Thank you!

**Comment by Refereer** [comment]
Hi @amranidev 

I found when the collections not have anything (I use where to filter it) then not resolve to execute the logic in closure

**Comment by amranidev** [comment]
Hi @Refereer, can you show me your code?

**Comment by Refereer** [comment]
`
mounted () {
    // Binding Collections
    this.$binding('payments', this.paymentFilteredDatabase)
      .then((payments) => {
        this.isLoaded = true
        this.$emit('isLoaded', true)
        if (payments.length > 0) {
          console.log('payments: ', payments)
        } else {
          console.log('there no payments on this accounts email: ', this.user.email)
        }
      })
  },
  computed: {
    paymentFilteredDatabase () {
      if (this.isAdmin) {
        return db.collection('payments')
      }
      return db.collection('payments').where('user_email', '==', this.user.email)
    }
  }
`

**Comment by amranidev** [comment]
if the promise is not resolved, I believe there must be an error or an exception, can you add `.catch` to the promise and see what kind of error it throws.

Thanks!
