### ISSUE TITLE
e.docChanges is not a function

### ISSUE THREAD

**Issue by notchris** [gdg-tangier/vue-firestore#25]
Currently getting this issue when loading the scripts via the CDN.
> Uncaught TypeError: e.docChanges is not a function

The same error occurs on the JS bin demo.
[https://i.imgur.com/xNvxMs1.png](url)

BTW, I've used this package in the past and it is great, thank you!

**Comment by amranidev** [comment]
Thank you!

**Comment by amranidev** [comment]
This is happening because there are some changes in firebase API, make sure to update your project to the latest release.
[Firebase release notes](https://firebase.google.com/support/releases).
