### ISSUE TITLE
Should have vue-define-reactive as dependency

### ISSUE THREAD

**Issue by minutuslausus** [gdg-tangier/vue-firestore#27]
I might be wrong, because I did not tested it thoroughly, but if I did not define the data property to bind to, then I got loads of error. (Like in your first example)

If I understand the source correctly in this situation the lib uses Vue.util.definReactive() here: https://github.com/gdg-tangier/vue-firestore/blob/master/src/vue-firestore.js#L17

I think it's a dependency on this lib: https://github.com/egoist/vue-define-reactive but can't seem to find it anywhere in the package.json

**Comment by amranidev** [comment]
Generally in Vue, if you wish your data to be reactive, you can use:

`Vue.util.defineReactive(instance, key, value)`

I did that because I need to bind the firebase collections/docs.

Example [vue-router](https://github.com/vuejs/vue-router/blob/dev/src/install.js#L27)

Thanks

**Comment by amranidev** [comment]
Hi @minutuslausus sorry for that late, I'm going to use `Vue.set` in another feature, the difference between `set` and defineReactive is that `set` can make an object and its elements (objects) reactive as well, check the following link [Reactivity in Depth](https://vuejs.org/v2/guide/reactivity.html).

Currently, I'm working on the feature that has been proposed by @asankulov, #20 which is basically bind a collection of objects in a given object within their keys.
