### ISSUE TITLE
"Define is not defined"

### ISSUE THREAD

**Issue by blvck237** [gdg-tangier/vue-firestore#3]
I've installed your module and i get the following error "Define is not defined"
![capture](https://user-images.githubusercontent.com/31737108/33131488-f68b3abc-cf96-11e7-9243-70568d02c70e.PNG)

**Comment by blurdylan** [comment]
I had the same issue when using `npm install`, this must be due to javascript closures,
To correct this, you can simply change the first line  of the `vue-firestore.js` file in `node_modules/vue-firestore/dist` to this:

```
(function(define) {define("Vue-firestore", [], function() { return /******/ (function(modules) { // webpackBootstrap

// Do not forget to close the parenthesis
```

**Comment by amranidev** [comment]
HI, Thanks for opening this issue, do you use CommonJS via Browsify or webpack ?,
It's recommended to use webpack with ES6.

**Comment by blurdylan** [comment]
I used webpack with electron-vuetify.

**Comment by amranidev** [comment]
A'right, I'm going to change the library target to UMD.
Could you please try v0.1.4 now?

**Comment by blvck237** [comment]
@amranidev  I am making use of a webpack and electron-vuetify

**Comment by blvck237** [comment]
@blurdylan you got the solution to the problem. The vue-firestore.js file had an issue with the define function. Thanks for your support
