### ISSUE TITLE
how to use server timestamps

### ISSUE THREAD

**Issue by jawainc** [gdg-tangier/vue-firestore#31]
as in the firstore docs : https://firebase.google.com/docs/firestore/manage-data/add-data

how can we use server timestamps  

    `created_at: firebase.firestore.FieldValue.serverTimestamp()`

or
`regions: firebase.firestore.FieldValue.arrayRemove("east_coast")`

**Comment by amranidev** [comment]
Hi @jawainc 
You can add timestamps or regions when you add the data to firestore.
for example:
```javascript
addData () {
   this.$firestore.myData.add({
        name: 'sample',
        created_at: firebase.firestore.FieldValue.serverTimestamp()
   })
}
```

**Comment by jawainc** [comment]
have to import `import { firebase } from '@firebase/app';` in every component where I want to use server timestamps.
following code example here: https://alligator.io/vuejs/vue-cloud-firestore/

**Comment by amranidev** [comment]
it's not recommended to import the firebase and firestore in every single component, that will make your app bundle bigger.
you can use `vuex` instead and import one state of firebase and firestore, then you can call them through `this.$store.state` in your components.

**Comment by jawainc** [comment]
Thanks for the idea, I did it from different approach
my firebase.js
```
import config from '@/resource/config';
import { firebase } from '@firebase/app';
import '@firebase/firestore';

const firebaseApp = firebase.initializeApp(config.fireBaseConfig);
let db = firebaseApp.firestore();
const settings = {timestampsInSnapshots: true};
db.settings(settings);

export {db, firebase};
```
exported firebase and db
now in vue component
`import { db, firebase } from './firebase';`

and it works
