### ISSUE TITLE
Bind key as `key` instead of `.key`

### ISSUE THREAD

**Issue by olivierkes** [gdg-tangier/vue-firestore#37]
Hi,
Thanks for vue-firestore, love it's simplicity.

I don't understand the logic behind the `.key` key. Could it be possible to bind keys as `key`instead?
I find it much easier to write `item.key` instead of `item[".key"]`

Or am I missing something?

**Comment by amranidev** [comment]
Hey @olivierkes thanks for opening this issue.

Basically, we've implemented `.key` prefix to identify the key of an object with a unique prefix, as you may know, using `key` without `.` is pretty common, so we don't want `vue-firestore` to use that as a key identifier for an object with a `key` property.

Does that make sense?

**Comment by olivierkes** [comment]
It makes sense, yet it's does not seem very elegent to me. I've used vue(x)fire that uses a non-enumerable `id` (which is consistent with the [firestore SDK for references](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference)), and it feels more natural.

Why not a custom option?

**Comment by amranidev** [comment]
If we define a non-enumerable prefix within an object in a collection with an `id` or `key` those still are can be overridden by properties right?

**Comment by olivierkes** [comment]
I think you can make it writable or not: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

To me the best option would be to have a non-enumerable prop `id` or `key` by default and the option to pass a string in the constructor for a custom prop name. 

That way the default behavior is the simplest, and in rare cases where db structures require a custom key or id, it can be accounted for.

**Comment by amranidev** [comment]
Ok, feel free to open a pull request for this 👍

**Comment by olivierkes** [comment]
Let me know what you think.
