### ISSUE TITLE
Reject on onSnapshot error

### ISSUE THREAD

**Issue by Jaimeer** [gdg-tangier/vue-firestore#4]
Please can you add reject in onSnapshot error in functions "collections" and "documents" to be able to detect for example "permission-denied" errors

Thanks

**Comment by amranidev** [comment]
Thanks for submitting this issue!!

The `bind` function already returns a promise, you can simply trigger that manually.
```javascript
  this.$binding("users", firebase.firestore().collection("users"))
  .then((users) => {
    console.log(users) // => __ob__: Observer
  }).catch(error) => {
      console.error(error.message)
  }
```

**Comment by Jaimeer** [comment]
Hi,
that only works if the problem is with the docChanges.forEach

`source.onSnapshot(doc => {
    doc.docChanges.forEach(snapshot => {
      ...
    }, reject)
  })
}`

You should add a new reject in onSnapshot
`source.onSnapshot(doc => {
    doc.docChanges.forEach(snapshot => {
      ...
    }, reject)
  }, reject)
}`

The same for the documents

`source.onSnapshot(doc => {
   ...
  }, reject)`

You can test it trying to access a collection in firestore where you don't have permissions

Regards

**Comment by Jaimeer** [comment]
Without the extra reject if you try the next code and receive an "Error: Missing or insufficient permissions.":

`component
      .$binding('tests', firebase.db.collection('tests'))
      .then(tests => {
        ...
      })
      .catch(error => {
        // Not enter
      })`

Regards

**Comment by amranidev** [comment]
Fixed!! 
Thanks :+1:
