### ISSUE TITLE
Manually binding doesn't resolve if collection empty

### ISSUE THREAD

**Issue by travisnguyen20** [gdg-tangier/vue-firestore#8]
I need to something after binding complete, but it seem doesn't work properly.
if I have 1 portfolio_items with portfolio_id = 'test' , portfolioLoading is set to false otherwise both "then" and "catch" doesn't execute. 
`this.$binding('portfolio_items', firebase.firestore().collection('portfolio_items').where('portfolio_id', '==', 'test'))
          .then((items) => {
            console.log(items)
            this.portfolioLoading = false
          }).catch((err) => {
            this.portfolioLoading = false
            console.log(err)
          })`

Anyone can help me out?

**Comment by travisnguyen20** [comment]
Seem update to version 0.2.6 solve this issue. so I close this

**Comment by amranidev** [comment]
Glad you solved it :+1:
