### ISSUE TITLE
How to Integrate Vue-Firestore to Quasar-app Framework (VueJS) ?

### ISSUE THREAD

**Issue by heliosnarcissus** [gdg-tangier/vue-firestore#9]
Hi I'm a newbie on quasar framework and would like to know if you have an idea how I can add this awesome vue-firestore library to my project folder? Working on web-app. :D

**Comment by lopugit** [comment]
have a look at app plugins 

http://quasar-framework.org/guide/app-plugins.html

I do it like this:

`
// /src/plugins/firestore.js
// import something here
import firebase from 'firebase'
import '@firebase/firestore'
var fs = initFirestore()

// leave the export, even if you don't use it
export default ({ app, router, Vue }) => {
	var firebaseApp
	if(!firebase.apps.length){
		firebaseApp = firebase.initializeApp(config)
	} else {
		firebaseApp = firebase.app()
	}
}

function initFirestore(){
	const config = {
		apiKey: "",
		authDomain: "",
		databaseURL: "",
		projectId: "",
		storageBucket: "",
		messagingSenderId: ""
	}
	const settings = {
		timestampsInSnapshots: true
	}

	if(!firebase.apps.length){
		firebase.initializeApp(config)
	} else {
		// F = firebase.app()
	}
	var fs = firebase.firestore() // firestore
	fs.settings(settings)
	fs.SetOptions = {merge: true}
	return fs

}`

And then in quasar.conf.js you'll put the string 'firestore' into your plugins array

`
module.exports = function(ctx) { return { plugins: [] } }
`

DAMN 19 days!! Sorry no one replied! That's a shame :'( Go over to discord quasar 

https://discordapp.com/channels/415874313728688138

There's heaps of active people there.

I don't even use the vue firestore wrapper but I might end up needing it.
